### ISSUE TITLE
Thousand separator to &nbsp;

### ISSUE THREAD

**Issue by Uelb** [mazipan/vue-currency-filter#26]
When someone displays a currency number, usually, the space should be a \&nbsp; so that the number is not breaked in the middle and unreadable. How would you implement such a feature, through a special option value or just convert the spaces passed in the option to \&nbsp;

**Comment by mazipan** [comment]
Just pass `space` in thousandsSeparator options or parameters.
See demo page.

**Comment by Uelb** [comment]
Sorry, my html code got converted, please re read my comment

**Comment by mazipan** [comment]
Can you give me sample or screenshot how empty space was unreadable in your HTML?
So I need to convert space to `&nbsp;`?

**Comment by mazipan** [comment]
Actually, this is not possible for now.
Because `filter` is only doing *value transformation* but not handle how those value is displayed.

Let's say I will give you string with `&nbsp;` as separator, still you can't display it as HTML unless you put in `v-html` attribute.

So, proper solution if you want `&nbsp;` as your separator is you pass `thousandSeparator` with `&nbsp;` string then you display in `v-html` like:

`v-html="$options.filters.currency(value, {thousandSeparator: '&nbsp;'})"

**Comment by Uelb** [comment]
That actually is a good enough solution ! Thank you very much for taking the time to help me.
It's a bit annoying because I can't do it in the default config but I guess it's the only way with the current version of vue

**Comment by Uelb** [comment]
FYI, you made a typo, it's thousandsSeparator and not thousandSeparator, may be good to change it for future readers
