### ISSUE TITLE
Ability to define multiple filters with different options

### ISSUE THREAD

**Issue by srchulo** [mazipan/vue-currency-filter#30]
I have some places in my app where fractionCount is 0, and some where it is 2. However, you can only define settings globally, which basically means I need to do something like this in half of my app:

`{{ money | currency({ fractionCount: 2 }) }}`

It would be really nice if the app supported multiple configurations with different filter names. In the meanwhile, I've done this:

```
Vue.filter('currency_no_fraction', function (value) {
  return Vue.options.filters.currency(value, {fractionCount: 0})
})
```

**Comment by mazipan** [comment]
I don't think it's common users needed.
We need to identify if it's need by usual users or it just your special case.
If it's special case, I prefer with your workaround creating your own filter base on this library implementation.

No offense ya, because when we accommodate all special case in the library, it will affect to code size that we need to deliver to our user.

I need to keep this library as lightweight as we can.

Btw, thanks for using this library @srchulo.
Your feedback also very good for this library.

Feel free to ask anything if you face any issue.
You also can create any PR.
